# Generated by Django 4.1 on 2022-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('e', 'Euro'), ('d', 'Dolar'), ('r', 'Ruble')], default='r', max_length=1),
        ),
    ]
